### ISSUE TITLE
Token Grabber (External Library) 

### ISSUE THREAD

**Issue by TDScripts** [imvast/Discord-Account-Creator#10]
[m0ney-dev](https://github.com/m0ney-dev) Has a issue already opened about this, I just wanted too try to bring some attention to  it,
But Vast's Library called configuration has a built-in token grabber/logger what ever you want to call it, 
https://pypi.org/project/confignation/#description

Removing
**Check Startup for unwanted apps!**
**If you have used this tool reset your password and run `pip uninstall confignation`  I also suggest reporting this faggot**

Whats Next 
**I might fork this project and maintain it also removing the token logger!**

**Comment by 10x30** [comment]
you should fork it and remove token logger
