### ISSUE TITLE
Identified errors

### ISSUE THREAD

**Issue by Ahosall** [imvast/Discord-Account-Creator#194]
### Module not found error
> resolved.
### InvalidHexColor
![image](https://github.com/imvast/Discord-Account-Creator/assets/49027157/79d2c636-5cf0-406e-9d70-f19f08709303)
> **Solution**
> 
> Use color names instead of HEX.
> ```py
> a = fg("dodger_blue_2")
> b = fg("royal_blue_1")
> c = fg("blue_violet")
> ```

**Comment by Ahosall** [comment]
> i just removed the colour libraries lmfao

😂 this is a solution too. But i believe that if he had specified the version in the requirements.txt this error would not appear...

**Comment by meeshyweeshy** [comment]
what proxies does this support?

**Comment by Hakoche** [comment]
Where can I find the proxies? I don't know much about computers

**Comment by Hakoche** [comment]
![Capture](https://github.com/imvast/Discord-Account-Creator/assets/143881209/e782fb87-b6f9-4c2a-a4f7-3c2c25f05f5f)
