### ISSUE TITLE
fix your f code

### ISSUE THREAD

**Issue by AndrexYT** [imvast/Discord-Account-Creator#210]

**Comment by AndrexYT** [comment]
and also i am having errors with the hex colors, i changed them to FFFFFF and all worked

**Comment by catdroutx** [comment]
this guy is a skidd. he copied it from a different guy

**Comment by imvast** [comment]
> this guy is a skidd. he copied it from a different guy

show :)

**Comment by AndrexYT** [comment]
> this guy is a skidd. he copied it from a different guy

true

**Comment by catdroutx** [comment]
> > this guy is a skidd. he copied it from a different guy
> 
> show :)

I lost the person which i got the info from but thats def aint your code. Developing token gens is extremely time intensive. I am building ine myself and its very difficult

**Comment by AndrexYT** [comment]
> > > this guy is a skidd. he copied it from a different guy
> > 
> > show :)
> 
> I lost the person which i got the info from but thats def aint your code. Developing token gens is extremely time intensive. I am building ine myself and its very difficult 

I am now making with others from GitHub Lua miner, you can join us 😊: https://discord.gg/FWr2Kzs8Dk

**Comment by imvast** [comment]
wompwomp
