### ISSUE TITLE
doesn't open

### ISSUE THREAD

**Issue by XDevyy** [imvast/Discord-Account-Creator#211]
ImportError: cannot import name 'Solver' from 'veilcord' (/root/Discord-Account-Creator/raid/lib/python3.11/site-packages/veilcord/__init__.py)

**Comment by BrawlMaks** [comment]
I'm getting the same problem
![jpg](https://github.com/imvast/Discord-Account-Creator/assets/126047270/aee560ed-5367-4ad6-919c-53793b5d2fa1)

**Comment by whoskingiroavalie4** [comment]
same issue

**Comment by vindetaVindetov** [comment]
YO NIGA 
![image](https://github.com/imvast/Discord-Account-Creator/assets/141769611/47ac9547-d476-40bf-8483-622526bff701)

**Comment by imvast** [comment]
maybe learn how to read a readme 🔥
