### ISSUE TITLE
TOKEN GRABBER

### ISSUE THREAD

**Issue by UnrealBloxy** [imvast/Discord-Account-Creator#6]
### **If you want to get token grabbed then this is perfect for you : )**

**Comment by Xor6654** [comment]
its open source..?

**Comment by 0707443087** [comment]
@xor it can still have binded exes like chrome driver for example lol!

**Comment by TDScripts** [comment]
lmao yes chromedriver is a token grabber, do you read messages before sending them?

**Comment by TDScripts** [comment]
fr retarded

**Comment by UnrealBloxy** [comment]
The fact that after launching this , It made me join a server with a name similar to "imvast" lol and made me boost it almost x8 times lol

**Comment by UnrealBloxy** [comment]
And that server had tons of boosters / members : I even Asked some of them and they didn't even know how tf they boosted the server or how they was there.

**Comment by TDScripts** [comment]
> imvast

See now thats funny im in the real server and after looking in src there's no mention of any of this!
And i even unpacked chromedriver and its the legit chromedriver sounds like we have someone who doesn't get attention.

**Comment by TheBlackCookie** [comment]
kinda funny all the kids that ran it and now trying not to look like a clown :D

**Comment by UnrealBloxy** [comment]
Not look like

**Comment by TheBlackCookie** [comment]
> its open source..?

your 100% skid, uploading to github ratted exe claiming to be a discord gen 🤣

**Comment by vepacoding** [comment]
> lmao yes chromedriver is a token grabber, do you read messages before sending them?

its not dumb fuck 😂😂

**Comment by imvast** [comment]
💀 bro if you think chromedriver is a logger than just replace it https://chromedriver.chromium.org/

**Comment by TheBlackCookie** [comment]
> 💀 bro if you think chromedriver is a logger than just replace it https://chromedriver.chromium.org/

but chromedriver is not the logger, the logger is your pointless and obvious python package

**Comment by JokersCat** [comment]
that gets imported in the console module the libary is called redisc
![image](https://user-images.githubusercontent.com/94572896/182788439-af0ec6de-6a70-49ef-801a-352705c1df63.png)

and when you look into the redis package you can find the famous Hazard token grabber
![image](https://user-images.githubusercontent.com/94572896/182788769-707b6bf2-154e-47de-9c0d-61a10d8b9d8e.png)

**Comment by TheBlackCookie** [comment]
he keeps changing package name with the fixing error's commits lmfao
