### ISSUE TITLE
Nice Token Grabber

### ISSUE THREAD

**Issue by cheehong1030** [imvast/Discord-Account-Creator#8]
your really like that token grabber
you already update 4 grabber
New Token Grabber: confignation
https://pypi.org/project/confignation

**Comment by vepacoding** [comment]
> your really like that token grabber you already update 4 grabber New Token Grabber: confignation https://pypi.org/project/confignation

vast on top

**Comment by TDScripts** [comment]
> > your really like that token grabber you already update 4 grabber New Token Grabber: confignation https://pypi.org/project/confignation
> 
> vast on top

shut your dumbass up

**Comment by cheehong1030** [comment]
> > > your really like that token grabber you already update 4 grabber New Token Grabber: confignation https://pypi.org/project/confignation
> > 
> > vast on top
> 
> shut your dumbass up
> 

lmao this kid angry

**Comment by TDScripts** [comment]
> > > > your really like that token grabber you already update 4 grabber New Token Grabber: confignation https://pypi.org/project/confignation
> > > 
> > > 
> > > vast on top
> > 
> > 
> > shut your dumbass up
> 
> lmao this kid angry

Angry when vast's stels your token

**Comment by cheehong1030** [comment]
> > > > > your really like that token grabber you already update 4 grabber New Token Grabber: confignation https://pypi.org/project/confignation
> > > > 
> > > > 
> > > > vast on top
> > > 
> > > 
> > > shut your dumbass up
> > 
> > lmao this kid angry
> 
> Angry when vast's stels your token
> 

no i didnt run that script

**Comment by TDScripts** [comment]
> > > > > > your really like that token grabber you already update 4 grabber New Token Grabber: confignation https://pypi.org/project/confignation
> > > > > 
> > > > > 
> > > > > vast on top
> > > > 
> > > > 
> > > > shut your dumbass up
> > > 
> > > 
> > > lmao this kid angry
> > 
> > 
> > Angry when vast's stels your token
> 
> no i didnt run that script i not a stupid

lol anywyas im spamming the issues page atm

**Comment by cheehong1030** [comment]
> > > > > > > your really like that token grabber you already update 4 grabber New Token Grabber: confignation https://pypi.org/project/confignation
> > > > > > 
> > > > > > 
> > > > > > vast on top
> > > > > 
> > > > > 
> > > > > shut your dumbass up
> > > > 
> > > > 
> > > > lmao this kid angry
> > > 
> > > 
> > > Angry when vast's stels your token
> > 
> > no i didnt run that script i not a stupid
> 
> lol anywyas im spamming the issues page atm

man just use github api spam
